### ISSUE TITLE
Enable smooth scrolling!

### ISSUE THREAD

**Issue by theprinceraj** [Bhaalu-69/Golf-Website#3]

**Comment by k7kaushal** [comment]
Hi @theprinceraj, 
I've been interested in working on open-source projects for quite a while now, Hacktoberfest seems to my starting point in this journey ahead, being new to open-source I feel your issue is a good first contribution for me to start with.
I would like the opportunity to get to know more details and contribute to this issue.

**Comment by theprinceraj** [comment]
Hi @k7kaushal , I assigned you this issue. You may start working on it. Good luck!

**Comment by k7kaushal** [comment]
Thanks @theprinceraj, will start working on it today!
I will create a pull request on 1st october so that it will be counted in my hacktoberfest contributions.

**Comment by theprinceraj** [comment]
Sure @k7kaushal 👍🏻🔥
